apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "plugin-site"
spec:
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
  restartPolicy: "Never"
  containers:
    - args: ["99d"]
      command: ["sleep"]
      env:
      image: "node:15"
      imagePullPolicy: "Always"
      name: "node"
      securityContext:
        privileged: false
      tty: true
    - args: ["99d"]
      command: ["sleep"]
      image: "mcr.microsoft.com/blobxfer:1.9.1"
      imagePullPolicy: "Always"
      name: "node"
      securityContext:
        privileged: false
      tty: true
